return {
	"and",              "break",            "do",               "else",             "elseif",
	"end",              "false",            "for",              "function",         "if",
	"in",               "local",            "nil",              "not",              "or",
	"repeat",           "return",           "then",             "true",             "until",
	"while",            "require",          "goto",             "self",             "print",
	"pairs",            "ipairs",           "next",             "tonumber",         "tostring",
	"type",             "pcall",            "xpcall",           "coroutine",        "table",
	"string",           "math",             "os",               "assert",           "error",
	"rawget",           "rawset",           "game",             "workspace",        "script",
	"Instance",         "Vector3",          "CFrame",           "Color3",           "UDim2",
	"Enum",             "wait",             "delay",            "spawn",            "tick",
	"time",             "Vector2",          "BrickColor",       "Region3",          "Ray",
	"task",             "RunService",       "UserInputService", "getgenv",          "loadstring",
	"GetChildren",      "GetDescendants",   "Connect",          "Play",             "Stop",
	"GetPlayers",       "Enabled",          "Texture",          "Color",            "Size",
	"Lifetime",         "Rate",             "Speed",            "Rotation",         "Transparency",
	"LightEmission",    "LightInfluence",   "SpreadAngle",      "SoundId",          "Volume",
	"PlaybackSpeed",    "Looped",           "Playing",          "Pitch",            "TimePosition",
	"RollOffMode",      "PlaybackRegionsEnabled", "CameraType", "FieldOfView",      "Focus",
	"ViewportSize",     "Active",           "BackgroundColor3", "BackgroundTransparency", "BorderColor3",
	"BorderSizePixel",  "ClipsDescendants", "Draggable",        "Position",         "Visible",
	"ZIndex",           "AnchorPoint",      "Brightness",       "Range",            "Shadows",
	"Angle",            "Health",           "MaxHealth",        "WalkSpeed",        "JumpPower",
	"HipHeight",        "RigType",          "DisplayName",      "NameDisplayDistance", "HealthDisplayDistance",
	"HealthDisplayType","MoveDirection",    "AutomaticScalingEnabled", "Anchored",   "CanCollide",
	"CanTouch",         "CanQuery",         "Locked",           "Massless",         "Reflectance",
	"Material",         "Orientation",      "Velocity",         "RotVelocity",      "AssemblyLinearVelocity",
	"AssemblyAngularVelocity", "Shape"
}
